# Generated by Django 5.2.8 on 2025-12-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temperature_max', models.FloatField(default=0)),
                ('compteur_alerte', models.IntegerField(default=0)),
                ('resolu', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('accuse_reception', models.BooleanField(default=False)),
            ],
        ),
    ]
