# Generated by Django 6.0 on 2026-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_operatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='last_increment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
